"""Pure Python ISF shader renderer with PyOpenGL and json5."""

from .errors import ISFError, ISFParseError, RenderingError, ShaderCompilationError
from .glsl_versions import get_supported_glsl_versions
from .parser import ISFMetadata, ISFParser
from .renderer import ISFRenderer
from .types import ISFColor, ISFPoint2D, ISFValue

# Version info — _version.py is generated by setuptools_scm at build time.
# Fall back gracefully when running from a source tree that hasn't been built.
try:
    from ._version import __version__
except ImportError:
    __version__ = "0.0.0+unknown"

__all__ = [
    "ISFColor",
    "ISFError",
    "ISFMetadata",
    "ISFParseError",
    "ISFParser",
    "ISFPoint2D",
    "ISFRenderer",
    "ISFValue",
    "RenderingError",
    "ShaderCompilationError",
    "__version__",
    "get_supported_glsl_versions",
]
