"""Pure Python ISF shader renderer with PyOpenGL and json5."""

from .renderer import ISFRenderer
from .parser import ISFParser, ISFMetadata
from .types import ISFColor, ISFPoint2D, ISFValue
from .errors import ISFError, ISFParseError, ShaderCompilationError, RenderingError
from .shader_compiler import get_supported_glsl_versions

# Version info — _version.py is generated by setuptools_scm at build time.
# Fall back gracefully when running from a source tree that hasn't been built.
try:
    from ._version import __version__
except ImportError:
    __version__ = "0.0.0+unknown"

__all__ = [
    # Main renderer
    'ISFRenderer',
    
    # Core components
    'ISFParser',
    'ISFMetadata',
    
    # Value types
    'ISFColor',
    'ISFPoint2D',
    'ISFValue',
    
    # Error types
    'ISFError',
    'ISFParseError',
    'ShaderCompilationError',
    'RenderingError',
    
    # Utility functions
    'get_supported_glsl_versions',
    
    # Version
    '__version__',
]
